### ISSUE TITLE
main.js:1 Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by ShootToThrill** [zanseven007/generator-zyy-h5#3]
我写了个class试了下能用不  然后就出这个了   删了还是有这个错

怎么破？

**Comment by zanseven007** [comment]
请问你页面上有没有加载 common.js? 请查看 webpack 配置里面的CommonsChunkPlugin 插件配置。此插件整合公共 js 代码，需在自己的 js 之前引用。

**Comment by zanseven007** [comment]
@ShootToThrill by the way，刚刚顺便修复了一个 htmlmin 不存在的 bug，不知道你有没有遇见，可进行脚手架重新安装，版本号为@0.2.21
